version: '3.8'
services:
  front:
    build: ./client
    container_name: nextjs-app
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd client && yarn dev"
    ports:
      - '3000:3000'

  backend:
    build: ./server
    container_name: fastapi-app
    volumes:
      - ./:/usr/src/app
    command: 'uvicorn server.fast_api.main:app --reload --host 0.0.0.0'
    ports:
      - 8000:8000
